server:
  port: 8080

logging:
  level:
    org.hibernate.orm.connections.pooling: OFF
    org.orm.connections.pooling: OFF
    org.hibernate.tool.schema: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3300/ecommerce-user?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      highlight_sql: true