version: '3.9'
services:
  ecommerce-mysql:
    image: mysql:latest
    container_name: mysql-ecommerce-practice
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce-practice
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./src/resources/volume/mysql/ecommerce-practice-data:/var/lib/mysql