version: '3.9'
services:
  ecommerce-mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./volumes/mysql/ecommerce-data:/var/lib/mysql