version: '3.9'
services:
  order-db:
    image: mysql:latest
    container_name: order-db
    restart: always
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce-order
    volumes:
      - ./volumes/mysql/order-data:/var/lib/mysql

  pay-db:
    image: mysql:latest
    container_name: pay-db
    restart: always
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce-pay
    volumes:
      - ./volumes/mysql/pay-data:/var/lib/mysql

  product-db:
    image: mysql:latest
    container_name: product-db
    restart: always
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce-product
    volumes:
      - ./volumes/mysql/product-data:/var/lib/mysql

  user-db:
    image: mysql:latest
    container_name: user-db
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce-user
    volumes:
      - ./volumes/mysql/user-data:/var/lib/mysql