server:
  port: 8081

logging:
  level:
    org.hibernate.orm.connections.pooling: OFF

spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    livereload: false
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3301/ecommerce-product?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update