package com.ecommerce

enum class OrderError {
    ORDERED_PRODUCT_DUPLICATED,
    ALREADY_PAID_ORDER,
    ORDER_NOT_CANCELABLE,
    NOT_FOUND_ORDERED_PRODUCT,
    ORDERED_PRODUCT_NOT_ORDERABLE,
    ORDERED_QUANTITY_GTE_ONE
}