spring:
  data:
    redis:
      lock:
        keyPrefix: DISTRIBUTED-LOCK
        retry: 5
        retryDelayMillis: 500
        lockTimeoutMillis: 40000
      cluster:
        nodes:
          - localhost:6001
          - localhost:16001
          - localhost:26001
          - localhost:6002
          - localhost:16002
          - localhost:26002
          - localhost:6003
          - localhost:16003
          - localhost:26003
        timeout: 1000ms
        lettuce:
          pool:
            max-active: 10
            min-idle: 2
            max-idle: 9
            max-wait: 100ms
