networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24
          gateway: 192.168.6.254

services:
  redis-master-001:
    container_name: redis-master-001
    image: redis:latest
    volumes:
      - ./redis.conf:/etc/redis.conf
    restart: always
    ports:
      - "6001:6379"
    networks:
      cluster:
        ipv4_address: 192.168.6.1
    command: [ "redis-server", "/etc/redis.conf", "--cluster-announce-ip", "192.168.6.1" ]

  redis-master-002:
    container_name: redis-master-002
    image: redis:latest
    volumes:
      - ./redis.conf:/etc/redis.conf
    restart: always
    ports:
      - "6002:6379"
    networks:
      cluster:
        ipv4_address: 192.168.6.2
    command: [ "redis-server", "/etc/redis.conf", "--cluster-announce-ip", "192.168.6.2" ]

  redis-master-003:
    container_name: redis-master-003
    image: redis:latest
    volumes:
      - ./redis.conf:/etc/redis.conf
    restart: always
    ports:
      - "6003:6379"
    networks:
      cluster:
        ipv4_address: 192.168.6.3
    command: [ "redis-server", "/etc/redis.conf", "--cluster-announce-ip", "192.168.6.3" ]
